<?php

// return [
//     'CERTIFICATE_CATEGORIES' => [
//         'incorporation' => 'Incorporation Certificates',
//         'regulatory' => 'Regulatory Certificates',
//         'hospital' => 'Hospital Certificates',
//         'environmental' => 'Environmental Certificates',
//         'other' => 'Other Certificates',
//     ],
//     'CERTIFICATE_LISTS' => [
//         'incorporation' => [
//             'Company Incorporation Certificate',
//             'Trade License/Business License',
//             'Shops Establishment Act Certificates',
//             'Import Export Code (IEC Certificate)',
//             'Udyam/MSME Certificate',
//             'PAN Card',
//             'GST Registration Certificate',
//             'ESI Registration Certificate',
//             'EPF Registration Certificate',
//         ],
//         'regulatory' => [
//             'Drug License',
//             'Good Manufacturing Practice Certificate (GMP)',
//             'WHO-GMP or cGMP Certificate',
//             'FDA Approval (US)',
//             'DCGI Approval (India)',
//             'CE Certification (European Conformity)',
//             'ISO 13485',
//             'BIS Certification (India)',
//             'CDSCO Registration (India)',
//             'ISO 9001:2015',
//             'ISO 14001',
//             'ISO 27001',
//         ],
//         'hospital' => [
//             'NABH Accreditation (India)',
//             'NABL Accreditation (India)',
//             'CAP Accreditation (USA)',
//         ],
//         'environmental' => [
//             'Biomedical Waste Management Authorization',
//             'Fire & Safety Clearance',
//             'Pollution Control Board Clearance',
//         ],
//         'other' => [
//             'Clinical Trial Approvals (From CDSCO or Ethics Committees)',
//             'AYUSH License',
//             'HACCP Certification',
//             'HIPAA Compliance (USA)',
//         ],
//     ],
//     'FINANCIAL_YEARS' => ['2020-21', '2021-22', '2022-23', '2023-24', '2024-25'],
//     'WORK_EXPERIENCE_AREAS' => ['Healthcare', 'IT', 'Construction', 'Consulting', 'Others'],
//     'EXPERIENCE_YEARS' => ['No Experience', '1', '2', '3', '4', '5'],
//     'INDIAN_STATES_AND_UTS' => [
//         "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana",
//         "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
//         "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
//         "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh",
//         "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry",
//     ],
//     'TENDER_INVITING_AUTHORITIES' => [
//         "State Health Society",
//         "State Ayush Society",
//         "Central Procurement Agency",
//         "Health Ministry",
//     ],
//     'OPEN_TENDER_LIST_OPTIONS' => [
//         "All Tenders",
//         "Latest Tender",
//         "Tenders with Corrigendum",
//         "Upcoming Tenders",
//         "Past Tenders",
//     ],
//     'ADDITIONAL_TENDER_TYPE_OPTIONS' => [
//         "All Type",
//         "Limited Tender",
//         "Open Tender",
//         "Short Tender",
//         "E-Auction",
//     ],
//     'COMPANY_REGISTRATION_TYPES' => [
//         "Public Limited Company (PLC)",
//         "Private Limited Company (PVT)",
//         "One Person Company (OPC)",
//         "Limited Liability Partnership Firm (LLP)",
//         "Partnership Firm",
//         "Society",
//         "Trust",
//         "Shops & Establishment Act",
//         "Section 8 Company",
//         "Others",
//     ],
//     'COMPANY_SECTOR_TYPES' => [
//         "Public Sector",
//         "Private Sector",
//         "Semi-government/Quasi-government",
//         "Joint Venture (JV)",
//         "Special Purpose Vehicle (SPV)",
//         "Special Purpose Entity (SPE)",
//         "Non-Profit/Non-Governmental Organizations (NGO)",
//         "Cooperative Society",
//         "Multinational Corporations (MNC)",
//         "Sole Proprietor",
//     ],
//     'NATURE_OF_BUSINESS_OPTIONS' => [
//         "Manufacturers/Producers",
//         "Service Provider",
//         "Suppliers/Vendors",
//         "Distributors",
//         "Wholesalers/Retailers",
//         "Consultants",
//         "Agents/Brokers",
//         "Others",
//     ],
//     'BUSINESS_SPECIALIZATION_OPTIONS' => [
//         "Healthcare Providers (Hospitals/Clinical Services)",
//         "Healthcare Providers (Diagnostics & Laboratory Services)",
//         "Healthcare Providers (Ambulatory Centers)",
//         "Medical Practitioners/Professionals",
//         "Pharmaceuticals & Biotech",
//         "Medical Equipment & Devices",
//         "Healthcare IT & Digital Health",
//         "Healthcare Support & Ancillary Services",
//         "Health Insurance & Payers",
//         "Wellness & Preventive Care",
//         "Regulatory Compliance & Consultancy",
//         "Hospital Infrastructure",
//     ],
//     'PROCUREMENT_CATEGORIES' => [
//         "Civil",
//         "Electrical",
//         "General",
//         "Healthcare",
//         "IT",
//     ],
//     'TENDER_NATURE_OPTIONS' => [
//         "Device",
//         "Medicine",
//         "Services",
//     ],
//     'EVENT_MODES' => ["Online", "Offline"],
//     'EVENT_STATUSES' => ["Active", "Inactive"],
//     'TENDER_TYPES' => [
//         'Online (e-tender)',
//         'Open Tender',
//         'Short Tender',
//         'Offline',
//     ],
//     'EMD_PAYMENT_MODES' => [
//         'Internet Payment Gateway (IPG)',
//         'Challan',
//         'Bank Guarantee',
//     ],
//     'DEPARTMENTS' => [
//         'State Health Society, Bihar (SHSB)',
//         'State Ayush Society, Bihar (SASB)',
//         'Health CE',
//     ],
//     'TAGS' => ['New Tender Release', 'Old Tender Update'],
// ];



return [
    'CERTIFICATE_CATEGORIES' => [
        'incorporation' => 'Incorporation Certificates',
        'regulatory' => 'Regulatory Certificates',
        'hospital' => 'Hospital Certificates',
        'environmental' => 'Environmental Certificates',
        'other' => 'Other Certificates',
    ],
    'CERTIFICATE_LISTS' => [
        'incorporation' => [
            'Company Incorporation Certificate',
            'Trade License/Business License/Shops Establishment Act Certificates',
            'Import Export Code (IEC Certificate)',
            'Udyam/MSME Certificate',
            'PAN Card',
            'GST Registration Certificate',
            'ESI Registration Certificate',
            'EPF Registration Certificate',
        ],
        'regulatory' => [
            'Drug License',
            'Good Manufacturing Practice Certificate (GMP)',
            'WHO-GMP or cGMP Certificate',
            'FDA Approval (US)',
            'DCGI Approval (India)',
            'CE Certification (European Conformity)',
            'ISO 13485',
            'BIS Certification (India)',
            'CDSCO Registration (India)',
            'ISO 9001:2015',
            'ISO 14001',
            'ISO 27001',
        ],
        'hospital' => [
            'NABH Accreditation (India)',
            'NABL Accreditation (India)',
            'CAP Accreditation (USA)',
        ],
        'environmental' => [
            'Biomedical Waste Management Authorization',
            'Fire & Safety Clearance',
            'Pollution Control Board Clearance',
        ],
        'other' => [
            'Clinical Trial Approvals (From CDSCO or Ethics Committees)',
            'AYUSH License',
            'HACCP Certification',
            'HIPAA Compliance (USA)',
        ],
    ],
    // 'FINANCIAL_YEARS' => ['2020-21', '2021-22', '2022-23', '2023-24', '2024-25'], // Align format with first set

    'FINANCIAL_YEARS' => [],
    'WORK_EXPERIENCE_AREAS' => ['Central Government', 'State Government', 'Central PSU', 'State PSU', 'Private Sector', 'Others'],
    'EXPERIENCE_YEARS' => ['No Experience', '1', '2', '3', '4', '5'],
    'INDIAN_STATES_AND_UTS' => [
        "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana",
        "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
        "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
        "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", "Chandigarh",
        "Dadra and Nagar Haveli and Daman and Diu", "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry",
    ],
    'TENDER_INVITING_AUTHORITIES' => [
        "State Health Society",
        "State Ayush Society",
        "Central Procurement Agency",
        "Health Ministry",
    ],
    'OPEN_TENDER_LIST_OPTIONS' => [
        "All Tenders",
        "Latest Tender",
        "Tenders with Corrigendum",
        "Upcoming Tenders",
        "Past Tenders",
    ],
    'ADDITIONAL_TENDER_TYPE_OPTIONS' => [
        "All Type",
        "Limited Tender",
        "Open Tender",
        "Short Tender",
        "E-Auction",
    ],
    'COMPANY_REGISTRATION_TYPES' => [
        "Public Limited Company (PLC)",
        "Private Limited Company (PVT)",
        "One Person Company (OPC)",
        "Limited Liability Partnership Firm (LLP)",
        "Partnership Firm",
        "Society",
        "Trust",
        "Shops & Establishment Act",
        "Section 8 Company",
        "Others",
    ],
    'COMPANY_SECTOR_TYPES' => [
        "Public Sector",
        "Private Sector",
        "Semi-government/Quasi-government",
        "Joint Venture (JV)",
        "Special Purpose Vehicle (SPV)",
        "Special Purpose Entity (SPE)",
        "Non-Profit/Non-Governmental Organizations (NGO)",
        "Cooperative Society",
        "Multinational Corporations (MNC)",
        "Sole Proprietor",
    ],
    'NATURE_OF_BUSINESS_OPTIONS' => [
        "Manufacturers/Producers",
        "Service Provider",
        "Suppliers/Vendors",
        "Distributors",
        "Wholesalers/Retailers",
        "Consultants",
        "Agents/Brokers",
        "Others",
    ],
    'BUSINESS_SPECIALIZATION_OPTIONS' => [
        "Healthcare Providers (Hospitals/Clinical Services)",
        "Healthcare Providers (Diagnostics & Laboratory Services)",
        "Healthcare Providers (Ambulatory Centers)",
        "Medical Practitioners/Professionals",
        "Pharmaceuticals & Biotech",
        "Medical Equipment & Devices",
        "Healthcare IT & Digital Health",
        "Healthcare Support & Ancillary Services",
        "Health Insurance & Payers",
        "Wellness & Preventive Care",
        "Regulatory Compliance & Consultancy",
        "Hospital Infrastructure",
    ],
    'PROCUREMENT_CATEGORIES' => [
        "Civil",
        "Electrical",
        "General",
        "Healthcare",
        "IT",
    ],
    'TENDER_NATURE_OPTIONS' => [
        "Device",
        "Medicine",
        "Services",
    ],
    'EVENT_MODES' => ["Online", "Offline"],
    'EVENT_STATUSES' => ["Active", "Inactive"],
    'TENDER_TYPES' => [
        'Online (e-tender)',
        'Open Tender',
        'Short Tender',
        'Offline',
    ],
    'COMPANY_TYPES' => [ // Added to match edit.blade.php
        'Online (e-tender)',
        'Open Tender',
        'Short Tender',
        'Offline',
    ],
    'EMD_PAYMENT_MODES' => [
        'Internet Payment Gateway (IPG)',
        'Challan',
        'Bank Guarantee',
    ],
    'DEPARTMENTS' => [
        'State Health Society, Bihar (SHSB)',
        'State Ayush Society, Bihar (SASB)',
        'Health CE',
    ],
    'TAGS' => ['New Tender Release', 'Old Tender Update'],
];


?>